apiVersion: v1
kind: Secret
metadata:
  name: job-backup-mongodb-secret
type: Opaque
data:
  MC_HOST_s3: dGVzdA==
  BAGCLI_DATABASE_URI: dGVzdA==
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-backup-mongodb
spec:
  concurrencyPolicy: Forbid
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: skyloud/job-backup-db:0.1.6
            args:
              - mongodb
            envFrom:
            - secretRef:
                name: job-backup-mongodb-secret
                optional: false
            env:
            - name: BAGCLI_RETENTION_TIME
              value: 7d
            imagePullPolicy: Always
            name: mongodb-backup
          tolerations: []