name: ci

on:
  release:
    types: [published]

env:
  IMAGE_TAG: ${{ github.event.release.tag_name || github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/job-backup-db:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/job-backup-db:${{ env.IMAGE_TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Update repo description
        env:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/job-backup-db
        run: |
         local code=$(jq -n --arg msg "$(<README.md)" \
           '{"registry":"registry-1.docker.io","full_description": $msg }' | \
               curl -s -o /dev/null  -L -w "%{http_code}" \
                  https://cloud.docker.com/v2/repositories/"${repository}"/ \
                  -d @- -X PATCH \
                  -H "Content-Type: application/json" \
                  -H "Authorization: JWT ${password}")
         if [[ "${code}" = "200" ]]; then
           printf "Successfully pushed README to Docker Hub"
         else
           printf "Unable to push README to Docker Hub, response code: %s\n" "${code}"
           exit 1
         fi